### ISSUE TITLE
Externalize chrome:// stylesheets

### ISSUE THREAD

**Issue by marcoscaceres** [emtwo/remote-newtab#11]
We should pull `chrome://` stylesheets out of the chrome:// URL to their own files. Any reason not to? 
- [x]  chrome://global/skin/
- [x] chrome://browser/content/searchSuggestionUI.css

**Comment by emtwo** [comment]
I think we definitely should do this.

**Comment by marcoscaceres** [comment]
ok, on it.

**Comment by marcoscaceres** [comment]
Ok, so it appears that we might not need either of those files. 

The  `chrome://global/skin/` seems to apply to XUL elements. And `searchSuggestionUI.css` doesn't exist anymore in the tree.
